version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: nodejschallenge
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nodejs-app

  db-test:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: nodejschallenge
      POSTGRES_DB: postgres_db_test
    ports:
      - 5433:5432
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    networks:
      - nodejs-app

  node-challenge-app:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
      - db-test
    networks:
      - nodejs-app

volumes:
  postgres-data:
  postgres-data-test:

networks:
  nodejs-app:
